"""empty message

Revision ID: 4c34f3d2995e
Revises: 72702ec4bfdf
Create Date: 2017-03-19 21:16:26.565000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c34f3d2995e'
down_revision = '72702ec4bfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_judges', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_judges', 'approved')
    # ### end Alembic commands ###
