"""empty message

Revision ID: 50ae466241f3
Revises: 
Create Date: 2017-03-22 19:30:16.154000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ae466241f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_sport_types')
    op.drop_table('tb_judge_levels')
    op.drop_table('tb_clubs')
    op.drop_table('tb_users_detail')
    op.drop_table('tb_users')
    op.drop_table('tb_judges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_judges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('judgeLevelId', sa.INTEGER(), nullable=False),
    sa.Column('sportTypeId', sa.INTEGER(), nullable=False),
    sa.Column('clubId', sa.INTEGER(), nullable=False),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('createdOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint(u'active IN (0, 1)'),
    sa.CheckConstraint(u'approved IN (0, 1)'),
    sa.ForeignKeyConstraint(['clubId'], [u'tb_clubs.id'], ),
    sa.ForeignKeyConstraint(['judgeLevelId'], [u'tb_judge_levels.id'], ),
    sa.ForeignKeyConstraint(['sportTypeId'], [u'tb_sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.BLOB(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('isAdmin', sa.BOOLEAN(), nullable=True),
    sa.Column('createdOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint(u'"isAdmin" IN (0, 1)'),
    sa.CheckConstraint(u'active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_users_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('register', sa.VARCHAR(length=20), nullable=False),
    sa.Column('familyname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('sportTypeId', sa.INTEGER(), nullable=False),
    sa.Column('clubId', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('contactName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('contactPhone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('contactAddress', sa.VARCHAR(length=200), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('createdOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint(u'active IN (0, 1)'),
    sa.CheckConstraint(u'sex IN (0, 1)'),
    sa.ForeignKeyConstraint(['clubId'], [u'tb_clubs.id'], ),
    sa.ForeignKeyConstraint(['sportTypeId'], [u'tb_sport_types.id'], ),
    sa.ForeignKeyConstraint(['userId'], [u'tb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register')
    )
    op.create_table('tb_clubs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('founder', sa.VARCHAR(length=80), nullable=False),
    sa.Column('createdDate', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('website', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('organiserName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('organiserEmail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('organiserPhone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('createdOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint(u'active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_judge_levels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('createdOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint(u'active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_sport_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('createdOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint(u'active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
