"""empty message

Revision ID: 6ad9aa59ac99
Revises: 7e13f0670b93
Create Date: 2017-03-09 00:27:40.992000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad9aa59ac99'
down_revision = '7e13f0670b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder', sa.String(length=80), nullable=False),
    sa.Column('createdDate', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('organiserName', sa.String(length=80), nullable=False),
    sa.Column('organiserEmail', sa.String(length=80), nullable=False),
    sa.Column('organiserPhone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_club')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_club',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('founder', sa.VARCHAR(length=80), nullable=False),
    sa.Column('createdDate', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('website', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('organiserName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('organiserEmail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('organiserPhone', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_clubs')
    # ### end Alembic commands ###
