"""empty message

Revision ID: 72702ec4bfdf
Revises: f8e8d10dd090
Create Date: 2017-03-19 21:12:04.798000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72702ec4bfdf'
down_revision = 'f8e8d10dd090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_clubs', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('tb_judge_levels', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('tb_judges', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('tb_sport_types', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_sport_types', 'active')
    op.drop_column('tb_judges', 'active')
    op.drop_column('tb_judge_levels', 'active')
    op.drop_column('tb_clubs', 'active')
    # ### end Alembic commands ###
