"""empty message

Revision ID: 8dd146a7e1cc
Revises: 8875ed1dc9ea
Create Date: 2017-03-22 21:13:44.552000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd146a7e1cc'
down_revision = '8875ed1dc9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder', sa.String(length=80), nullable=False),
    sa.Column('createdDate', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('organiserName', sa.String(length=80), nullable=False),
    sa.Column('organiserEmail', sa.String(length=80), nullable=False),
    sa.Column('organiserPhone', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_judge_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_sport_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('judgeLevelId', sa.Integer(), nullable=False),
    sa.Column('sportTypeId', sa.Integer(), nullable=False),
    sa.Column('clubId', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['clubId'], ['tb_clubs.id'], ),
    sa.ForeignKeyConstraint(['judgeLevelId'], ['tb_judge_levels.id'], ),
    sa.ForeignKeyConstraint(['sportTypeId'], ['tb_sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_users_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register', sa.String(length=20), nullable=False),
    sa.Column('familyname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('sportTypeId', sa.Integer(), nullable=False),
    sa.Column('clubId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('contactName', sa.String(length=80), nullable=False),
    sa.Column('contactPhone', sa.String(length=20), nullable=False),
    sa.Column('contactAddress', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['clubId'], ['tb_clubs.id'], ),
    sa.ForeignKeyConstraint(['sportTypeId'], ['tb_sport_types.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_users_detail')
    op.drop_table('tb_judges')
    op.drop_table('tb_users')
    op.drop_table('tb_sport_types')
    op.drop_table('tb_judge_levels')
    op.drop_table('tb_clubs')
    # ### end Alembic commands ###
