"""empty message

Revision ID: f8e8d10dd090
Revises: e9a213c393ff
Create Date: 2017-03-18 14:26:53.723000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e8d10dd090'
down_revision = 'e9a213c393ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_judge_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('judgeLevelId', sa.Integer(), nullable=False),
    sa.Column('sportTypeId', sa.Integer(), nullable=False),
    sa.Column('clubId', sa.Integer(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['clubId'], ['tb_clubs.id'], ),
    sa.ForeignKeyConstraint(['judgeLevelId'], ['tb_judge_levels.id'], ),
    sa.ForeignKeyConstraint(['sportTypeId'], ['tb_sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_judges')
    op.drop_table('tb_judge_levels')
    # ### end Alembic commands ###
